version: 0.0
os: linux
files:
  - source: build/libs/url-shortener-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/web/
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 500
      runas: ec2-user