version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/web/
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 500
      runas: root